# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven - dev branch

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch from GitHub
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: List target directory
        run: |
          cd target
          ls -a

      - name: Cache for Maven
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Package resource pack
        run: |
          cd resourcepack
          zip -r mcide.zip ./*

      - name: Prepare files for release upload
        run: |
            mkdir upload
            cp resourcepack/mcide.zip upload
            cp target/mcide*.jar upload

      - name: Get realease version from pom.xml
        id: get-version
        uses: jactions/maven-version@v1.0.0

      - name: Upload files to a GitHub release
        uses: svenstaro/upload-release-action@2.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: upload/*
          tag: dev-${{ steps.get-version.outputs.version }}
          overwrite: true
          file_glob: true